
import java.util.Random;
import oyuncular.Bilgisayar;
import oyuncular.Kullanici;
import sporcular.Sporcu;

public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    Kullanici kullanici;
    Bilgisayar bilgisayar;
    String futbolcuArka="images/futbolcuArka.png";
    String basketbolcuArka="images/basketbolcuArka.png";
    boolean futbolcuMu=true;
   
    public Game(Kullanici kullanici,Bilgisayar bilgisayar) {
        initComponents();
        this.kullanici =kullanici;
        this.bilgisayar=bilgisayar;
        
      btnKullanici1.setIcon(new javax.swing.ImageIcon(getClass().getResource(kullanici.sporcular.get(0).getResimYolu())));
      btnKullanici2.setIcon(new javax.swing.ImageIcon(getClass().getResource(kullanici.sporcular.get(1).getResimYolu())));
      btnKullanici3.setIcon(new javax.swing.ImageIcon(getClass().getResource(kullanici.sporcular.get(2).getResimYolu())));
      btnKullanici4.setIcon(new javax.swing.ImageIcon(getClass().getResource(kullanici.sporcular.get(3).getResimYolu())));
      btnKullanici5.setIcon(new javax.swing.ImageIcon(getClass().getResource(kullanici.sporcular.get(4).getResimYolu())));
      btnKullanici6.setIcon(new javax.swing.ImageIcon(getClass().getResource(kullanici.sporcular.get(5).getResimYolu())));
      btnKullanici7.setIcon(new javax.swing.ImageIcon(getClass().getResource(kullanici.sporcular.get(6).getResimYolu())));
      btnKullanici8.setIcon(new javax.swing.ImageIcon(getClass().getResource(kullanici.sporcular.get(7).getResimYolu())));
      
      btnBilgisayar1.setIcon(new javax.swing.ImageIcon(getClass().getResource(basketbolcuArka)));
      btnBilgisayar2.setIcon(new javax.swing.ImageIcon(getClass().getResource(basketbolcuArka)));
      btnBilgisayar3.setIcon(new javax.swing.ImageIcon(getClass().getResource(basketbolcuArka)));
      btnBilgisayar4.setIcon(new javax.swing.ImageIcon(getClass().getResource(basketbolcuArka)));
      btnBilgisayar5.setIcon(new javax.swing.ImageIcon(getClass().getResource(futbolcuArka)));
      btnBilgisayar6.setIcon(new javax.swing.ImageIcon(getClass().getResource(futbolcuArka)));
      btnBilgisayar7.setIcon(new javax.swing.ImageIcon(getClass().getResource(futbolcuArka)));
      btnBilgisayar8.setIcon(new javax.swing.ImageIcon(getClass().getResource(futbolcuArka)));
        
    }

    private Game() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnKullanici6 = new javax.swing.JButton();
        btnKullanici5 = new javax.swing.JButton();
        btnKullanici3 = new javax.swing.JButton();
        btnKullanici2 = new javax.swing.JButton();
        btnKullanici1 = new javax.swing.JButton();
        btnKullanici4 = new javax.swing.JButton();
        btnKullanici7 = new javax.swing.JButton();
        btnKullanici8 = new javax.swing.JButton();
        btnBilgisayar3 = new javax.swing.JButton();
        btnBilgisayar4 = new javax.swing.JButton();
        btnBilgisayar5 = new javax.swing.JButton();
        btnBilgisayar7 = new javax.swing.JButton();
        btnKullaniciKarsilasma = new javax.swing.JButton();
        btnBilgisayar6 = new javax.swing.JButton();
        btnBilgisayar8 = new javax.swing.JButton();
        btnBilgisayar2 = new javax.swing.JButton();
        btnBilgisayarKarsilasma = new javax.swing.JButton();
        btnBilgisayar1 = new javax.swing.JButton();
        lblOzellik = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblBigisayarSkor = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblKullaniciSkor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnKullanici6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKullanici6ActionPerformed(evt);
            }
        });

        btnKullanici5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKullanici5ActionPerformed(evt);
            }
        });

        btnKullanici3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKullanici3ActionPerformed(evt);
            }
        });

        btnKullanici2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKullanici2ActionPerformed(evt);
            }
        });

        btnKullanici1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKullanici1ActionPerformed(evt);
            }
        });

        btnKullanici4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKullanici4ActionPerformed(evt);
            }
        });

        btnKullanici7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKullanici7ActionPerformed(evt);
            }
        });

        btnKullanici8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKullanici8ActionPerformed(evt);
            }
        });

        btnBilgisayar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBilgisayar7ActionPerformed(evt);
            }
        });

        btnBilgisayarKarsilasma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBilgisayarKarsilasmaActionPerformed(evt);
            }
        });

        lblOzellik.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblOzellik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOzellik.setText("Seçilen Özellik");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VS");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("KULLANICI");

        lblBigisayarSkor.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        lblBigisayarSkor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBigisayarSkor.setText("Skor");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("BİLGİSAYAR");

        lblKullaniciSkor.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        lblKullaniciSkor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKullaniciSkor.setText("Skor");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBigisayarSkor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnBilgisayarKarsilasma, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblOzellik, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnKullaniciKarsilasma, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                            .addComponent(lblKullaniciSkor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnBilgisayar1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBilgisayar2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBilgisayar3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBilgisayar4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBilgisayar5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBilgisayar6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBilgisayar7, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBilgisayar8, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnKullanici1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(btnKullanici2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnKullanici3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnKullanici4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnKullanici5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnKullanici6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnKullanici7, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnKullanici8, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBilgisayar5, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBilgisayar6, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBilgisayar8, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBilgisayar7, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBilgisayar4, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBilgisayar1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBilgisayar3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBilgisayar2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOzellik, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnKullaniciKarsilasma, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBilgisayarKarsilasma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblBigisayarSkor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblKullaniciSkor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKullanici8, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKullanici2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKullanici3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKullanici5, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKullanici6, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKullanici4, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnKullanici1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnKullanici7, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBilgisayarKarsilasmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBilgisayarKarsilasmaActionPerformed
        
    }//GEN-LAST:event_btnBilgisayarKarsilasmaActionPerformed

    private void btnBilgisayar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBilgisayar7ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_btnBilgisayar7ActionPerformed

    private void btnKullanici3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKullanici3ActionPerformed
     
        int sayac=0;
        for(Sporcu sporcu:bilgisayar.sporcular){
            if(sporcu.isKartKullanildiMi()==false){
                sayac++;
            }
        }
        if(futbolcuMu||sayac==1){
            btnKullanici3.setEnabled(false);
        btnKullaniciKarsilasma.setIcon(new javax.swing.ImageIcon(getClass().getResource(kullanici.sporcular.get(2).getResimYolu())));    
        int i=bilgisayar.KartSec(0);
        btnBilgisayarKarsilasma.setIcon(new javax.swing.ImageIcon(getClass().getResource(bilgisayar.sporcular.get(i).getResimYolu())));
        bilgisayarKartAt(i);
        int r=new Random().nextInt(3);
        
        lblOzellik.setText(ozellikSec0(r));
       int k = karsilastir(kullanici.sporcular.get(0),bilgisayar.sporcular.get(i),r);
       
       if(k ==0){
           kullanici.setSkor(kullanici.getSkor()+1);
       }else if(k ==1){
           bilgisayar.setSkor(bilgisayar.getSkor()+1);
       }else{
          btnKullaniciKarsilasma.setIcon(null);
          btnBilgisayarKarsilasma.setIcon(null);
           bilgisayarKartTopla(i);
          btnKullanici3.setEnabled(true);
          bilgisayar.sporcular.get(i).setKartKullanildiMi(false);
       }
       
       lblKullaniciSkor.setText(Integer.toString(kullanici.getSkor()));
       lblBigisayarSkor.setText(Integer.toString(bilgisayar.getSkor()));
       futbolcuMu= false;
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnKullanici3ActionPerformed

    private void btnKullanici1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKullanici1ActionPerformed

        int sayac=0;
        for(Sporcu sporcu:bilgisayar.sporcular){
            if(sporcu.isKartKullanildiMi()==false){
                sayac++;
            }
        }
        if(futbolcuMu||sayac==1){
            btnKullanici1.setEnabled(false);
        btnKullaniciKarsilasma.setIcon(new javax.swing.ImageIcon(getClass().getResource(kullanici.sporcular.get(0).getResimYolu())));
        
        int i=bilgisayar.KartSec(0);
        btnBilgisayarKarsilasma.setIcon(new javax.swing.ImageIcon(getClass().getResource(bilgisayar.sporcular.get(i).getResimYolu())));
        bilgisayarKartAt(i);
        int r=new Random().nextInt(3);
        
        lblOzellik.setText(ozellikSec0(r));
       int k = karsilastir(kullanici.sporcular.get(0),bilgisayar.sporcular.get(i),r);
       
       if(k ==0){
           kullanici.setSkor(kullanici.getSkor()+1);
       }else if(k ==1){
           bilgisayar.setSkor(bilgisayar.getSkor()+1);
       }else{
          btnKullaniciKarsilasma.setIcon(null);
          btnBilgisayarKarsilasma.setIcon(null);
           bilgisayarKartTopla(i);
          btnKullanici1.setEnabled(true);
           bilgisayar.sporcular.get(i).setKartKullanildiMi(false);
       }
       
       lblKullaniciSkor.setText(Integer.toString(kullanici.getSkor()));
       lblBigisayarSkor.setText(Integer.toString(bilgisayar.getSkor()));
       futbolcuMu=false;
        }
        
        
        
        
    }//GEN-LAST:event_btnKullanici1ActionPerformed

    private void btnKullanici2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKullanici2ActionPerformed
        // TODO add your handling code here
        
        int sayac=0;
        for(Sporcu sporcu:bilgisayar.sporcular){
            if(sporcu.isKartKullanildiMi()==false){
                sayac++;
            }
        }
        if(futbolcuMu||sayac==1){
            
            btnKullanici2.setEnabled(false);
        btnKullaniciKarsilasma.setIcon(new javax.swing.ImageIcon(getClass().getResource(kullanici.sporcular.get(1).getResimYolu())));
        
        int i=bilgisayar.KartSec(0);
        btnBilgisayarKarsilasma.setIcon(new javax.swing.ImageIcon(getClass().getResource(bilgisayar.sporcular.get(i).getResimYolu())));
        bilgisayarKartAt(i);
        int r=new Random().nextInt(3);
        
        lblOzellik.setText(ozellikSec0(r));
       int k = karsilastir(kullanici.sporcular.get(0),bilgisayar.sporcular.get(i),r);
       
       if(k ==0){
           kullanici.setSkor(kullanici.getSkor()+1);
       }else if(k ==1){
           bilgisayar.setSkor(bilgisayar.getSkor()+1);
       }else{
          btnKullaniciKarsilasma.setIcon(null);
          btnBilgisayarKarsilasma.setIcon(null);
           bilgisayarKartTopla(i);
          btnKullanici2.setEnabled(true);
           bilgisayar.sporcular.get(i).setKartKullanildiMi(false);
       }
       
       lblKullaniciSkor.setText(Integer.toString(kullanici.getSkor()));
       lblBigisayarSkor.setText(Integer.toString(bilgisayar.getSkor()));
       futbolcuMu= false;
        }
      
    }//GEN-LAST:event_btnKullanici2ActionPerformed

    private void btnKullanici4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKullanici4ActionPerformed

             int sayac=0;
        for(Sporcu sporcu:bilgisayar.sporcular){
            if(sporcu.isKartKullanildiMi()==false){
                sayac++;
            }
        }
             if(futbolcuMu||sayac==1){
                 btnKullanici4.setEnabled(false);
        btnKullaniciKarsilasma.setIcon(new javax.swing.ImageIcon(getClass().getResource(kullanici.sporcular.get(3).getResimYolu())));
        
        int i=bilgisayar.KartSec(0);
        btnBilgisayarKarsilasma.setIcon(new javax.swing.ImageIcon(getClass().getResource(bilgisayar.sporcular.get(i).getResimYolu())));
        bilgisayarKartAt(i);
        int r=new Random().nextInt(3);
        
        lblOzellik.setText(ozellikSec0(r));
       int k = karsilastir(kullanici.sporcular.get(0),bilgisayar.sporcular.get(i),r);
       
       if(k ==0){
           kullanici.setSkor(kullanici.getSkor()+1);
       }else if(k ==1){
           bilgisayar.setSkor(bilgisayar.getSkor()+1);
       }else{
          btnKullaniciKarsilasma.setIcon(null);
          btnBilgisayarKarsilasma.setIcon(null);
           bilgisayarKartTopla(i);
          btnKullanici4.setEnabled(true);
           bilgisayar.sporcular.get(i).setKartKullanildiMi(false);
       }
       
       lblKullaniciSkor.setText(Integer.toString(kullanici.getSkor()));
       lblBigisayarSkor.setText(Integer.toString(bilgisayar.getSkor()));
       futbolcuMu =false;
             }
             
    }//GEN-LAST:event_btnKullanici4ActionPerformed

    private void btnKullanici5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKullanici5ActionPerformed
        int sayac=0;
        for(Sporcu sporcu:bilgisayar.sporcular){
            if(sporcu.isKartKullanildiMi()==false){
                sayac++;
            }
        }
        if(!futbolcuMu||sayac==1){
            btnKullanici5.setEnabled(false);
        btnKullaniciKarsilasma.setIcon(new javax.swing.ImageIcon(getClass().getResource(kullanici.sporcular.get(4).getResimYolu())));
        
        int i=bilgisayar.KartSec(1);
        btnBilgisayarKarsilasma.setIcon(new javax.swing.ImageIcon(getClass().getResource(bilgisayar.sporcular.get(i).getResimYolu())));
        bilgisayarKartAt(i);
        int r=new Random().nextInt(3);
        
        lblOzellik.setText(ozellikSec1(r));
       int k = karsilastir(kullanici.sporcular.get(0),bilgisayar.sporcular.get(i),r);
       
       if(k ==0){
           kullanici.setSkor(kullanici.getSkor()+1);
       }else if(k ==1){
           bilgisayar.setSkor(bilgisayar.getSkor()+1);
       }else{
          btnKullaniciKarsilasma.setIcon(null);
          btnBilgisayarKarsilasma.setIcon(null);
           bilgisayarKartTopla(i);
          btnKullanici5.setEnabled(true);
           bilgisayar.sporcular.get(i).setKartKullanildiMi(false);
       }
       
       lblKullaniciSkor.setText(Integer.toString(kullanici.getSkor()));
       lblBigisayarSkor.setText(Integer.toString(bilgisayar.getSkor()));
       futbolcuMu=true;
        }
        
        
    }//GEN-LAST:event_btnKullanici5ActionPerformed

    private void btnKullanici6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKullanici6ActionPerformed
        // TODO add your handling code here:
        int sayac=0;
        for(Sporcu sporcu:bilgisayar.sporcular){
            if(sporcu.isKartKullanildiMi()==false){
                sayac++;
            }
        }
        if(!futbolcuMu||sayac==1){
            btnKullanici6.setEnabled(false);
        btnKullaniciKarsilasma.setIcon(new javax.swing.ImageIcon(getClass().getResource(kullanici.sporcular.get(5).getResimYolu())));
         
        int i=bilgisayar.KartSec(1);
        btnBilgisayarKarsilasma.setIcon(new javax.swing.ImageIcon(getClass().getResource(bilgisayar.sporcular.get(i).getResimYolu())));
        bilgisayarKartAt(i);
        int r=new Random().nextInt(3);
        
        lblOzellik.setText(ozellikSec1(r));
       int k = karsilastir(kullanici.sporcular.get(0),bilgisayar.sporcular.get(i),r);
       
       if(k ==0){
           kullanici.setSkor(kullanici.getSkor()+1);
       }else if(k ==1){
           bilgisayar.setSkor(bilgisayar.getSkor()+1);
       }else{
          btnKullaniciKarsilasma.setIcon(null);
          btnBilgisayarKarsilasma.setIcon(null);
           bilgisayarKartTopla(i);
          btnKullanici6.setEnabled(true);
           bilgisayar.sporcular.get(i).setKartKullanildiMi(false);
       }
       
       lblKullaniciSkor.setText(Integer.toString(kullanici.getSkor()));
       lblBigisayarSkor.setText(Integer.toString(bilgisayar.getSkor()));
       futbolcuMu=true;
        }
        
    }//GEN-LAST:event_btnKullanici6ActionPerformed

    private void btnKullanici7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKullanici7ActionPerformed
        // TODO add your handling code here:
        int sayac=0;
        for(Sporcu sporcu:bilgisayar.sporcular){
            if(sporcu.isKartKullanildiMi()==false){
                sayac++;
            }
        }
        if(!futbolcuMu||sayac==1){
             btnKullanici7.setEnabled(false);
        btnKullaniciKarsilasma.setIcon(new javax.swing.ImageIcon(getClass().getResource(kullanici.sporcular.get(6).getResimYolu())));
         
        int i=bilgisayar.KartSec(1);
        btnBilgisayarKarsilasma.setIcon(new javax.swing.ImageIcon(getClass().getResource(bilgisayar.sporcular.get(i).getResimYolu())));
        bilgisayarKartAt(i);
        int r=new Random().nextInt(3);
        
        lblOzellik.setText(ozellikSec1(r));
       int k = karsilastir(kullanici.sporcular.get(0),bilgisayar.sporcular.get(i),r);
       
       if(k ==0){
           kullanici.setSkor(kullanici.getSkor()+1);
       }else if(k ==1){
           bilgisayar.setSkor(bilgisayar.getSkor()+1);
       }else{
          btnKullaniciKarsilasma.setIcon(null);
          btnBilgisayarKarsilasma.setIcon(null);
           bilgisayarKartTopla(i);
          btnKullanici7.setEnabled(true);
           bilgisayar.sporcular.get(i).setKartKullanildiMi(false);
       }
       
       lblKullaniciSkor.setText(Integer.toString(kullanici.getSkor()));
       lblBigisayarSkor.setText(Integer.toString(bilgisayar.getSkor()));
       futbolcuMu =true;
        }
       
    }//GEN-LAST:event_btnKullanici7ActionPerformed

    private void btnKullanici8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKullanici8ActionPerformed
        // TODO add your handling code here:
        int sayac=0;
        for(Sporcu sporcu:bilgisayar.sporcular){
            if(sporcu.isKartKullanildiMi()==false){
                sayac++;
            }
        }
        if(!futbolcuMu||sayac==1){
            btnKullanici8.setEnabled(false);
        btnKullaniciKarsilasma.setIcon(new javax.swing.ImageIcon(getClass().getResource(kullanici.sporcular.get(7).getResimYolu())));
         
        int i=bilgisayar.KartSec(1);
        btnBilgisayarKarsilasma.setIcon(new javax.swing.ImageIcon(getClass().getResource(bilgisayar.sporcular.get(i).getResimYolu())));
        bilgisayarKartAt(i);
        int r=new Random().nextInt(3);
        
        lblOzellik.setText(ozellikSec1(r));
       int k = karsilastir(kullanici.sporcular.get(0),bilgisayar.sporcular.get(i),r);
       
       if(k ==0){
           kullanici.setSkor(kullanici.getSkor()+1);
       }else if(k ==1){
           bilgisayar.setSkor(bilgisayar.getSkor()+1);
       }else{
          btnKullaniciKarsilasma.setIcon(null);
          btnBilgisayarKarsilasma.setIcon(null);
           bilgisayarKartTopla(i);
          btnKullanici8.setEnabled(true);
           bilgisayar.sporcular.get(i).setKartKullanildiMi(false);
          
          
       }
       
       lblKullaniciSkor.setText(Integer.toString(kullanici.getSkor()));
       lblBigisayarSkor.setText(Integer.toString(bilgisayar.getSkor()));
       futbolcuMu=true;
        }
        
    }//GEN-LAST:event_btnKullanici8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }
    
    public String ozellikSec0(int i){
        
        if(i ==0){
            return "PENALTI";
        }else if(i==1){
            return  "SERBEST VURUŞ";
        }else{
            return "KARŞI KARŞIYA";
        }
        
   
    }
    
     public String ozellikSec1(int i){
        
        if(i ==0){
            return "İKİLİK";
        }else if(i==1){
            return  "ÜÇLÜK";
        }else{
            return "SERBEST ATIŞ";
        }
        
   
    }
            
    public int karsilastir(Sporcu kullanici,Sporcu bilgisayar,int i){
        if(kullanici.sporcuPuaniGoster(i)>bilgisayar.sporcuPuaniGoster(i)){
            return 0;
        }else if(kullanici.sporcuPuaniGoster(i)<bilgisayar.sporcuPuaniGoster(i)){
            return 1;
        }else 
            return -1;
            
    }
    
    public void bilgisayarKartAt(int i){
        switch (i) {
            case 0:
                btnBilgisayar1.setEnabled(false);
                break;
            case 1:
                btnBilgisayar2.setEnabled(false);
                break;
            case 2:
                btnBilgisayar3.setEnabled(false);
                break;
            case 3:
                btnBilgisayar4.setEnabled(false);
                break;
            case 4:
                btnBilgisayar5.setEnabled(false);
                break;
            case 5:
                btnBilgisayar6.setEnabled(false);
                break;
            case 6:
                btnBilgisayar7.setEnabled(false);
                break;
            case 7:
                btnBilgisayar8.setEnabled(false);
                break;
            default:
                break;
        }
    }
    
       public void bilgisayarKartTopla(int i){
        switch (i) {
            case 0:
                btnBilgisayar1.setEnabled(true);
                break;
            case 1:
                btnBilgisayar2.setEnabled(true);
                break;
            case 2:
                btnBilgisayar3.setEnabled(true);
                break;
            case 3:
                btnBilgisayar4.setEnabled(true);
                break;
            case 4:
                btnBilgisayar5.setEnabled(true);
                break;
            case 5:
                btnBilgisayar6.setEnabled(true);
                break;
            case 6:
                btnBilgisayar7.setEnabled(true);
                break;
            case 7:
                btnBilgisayar8.setEnabled(true);
                break;
            default:
                break;
        }
           
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBilgisayar1;
    private javax.swing.JButton btnBilgisayar2;
    private javax.swing.JButton btnBilgisayar3;
    private javax.swing.JButton btnBilgisayar4;
    private javax.swing.JButton btnBilgisayar5;
    private javax.swing.JButton btnBilgisayar6;
    private javax.swing.JButton btnBilgisayar7;
    private javax.swing.JButton btnBilgisayar8;
    private javax.swing.JButton btnBilgisayarKarsilasma;
    private javax.swing.JButton btnKullanici1;
    private javax.swing.JButton btnKullanici2;
    private javax.swing.JButton btnKullanici3;
    private javax.swing.JButton btnKullanici4;
    private javax.swing.JButton btnKullanici5;
    private javax.swing.JButton btnKullanici6;
    private javax.swing.JButton btnKullanici7;
    private javax.swing.JButton btnKullanici8;
    private javax.swing.JButton btnKullaniciKarsilasma;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBigisayarSkor;
    private javax.swing.JLabel lblKullaniciSkor;
    private javax.swing.JLabel lblOzellik;
    // End of variables declaration//GEN-END:variables
}
